% load post-ICA data
eeglab
s.subj_data_path = 'C:\Users\Zeno\Desktop\VRCodesMain'; % Path of the file
EEG = eeg_checkset( EEG );
EEG = pop_loadset('filename','Walking_Anxiety_postICA.set','filepath','C:\\Users\\Zeno\\Desktop\\VRCodesMain\\');
EEG = eeg_checkset( EEG );

% USE GUI
name = 'Walking_Anxiety_postICA';
EEG = pop_saveset( EEG, 'filename',[name '.set'],'filepath',s.subj_data_path);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET); 
eeglab redraw

% save ica information - or load if already saved
name = 'Anxiety';
icaact = EEG.icaact;
icawinv = EEG.icawinv;
icasphere = EEG.icasphere;
icaweights = EEG.icaweights;
icachansind = EEG.icachansind;
good = EEG.good;  
eyes = EEG.eyes;
bad = EEG.bad;  
pathname= [name , '_ICA.mat' ];
% update filename, based on trial
save(pathname,'icaact','icawinv','icasphere','icaweights','icachansind','good','eyes','bad');

load Anxiety_ICA.mat

% open continuous data (epoch_set - channel location formation
EEG = eeg_checkset( EEG );
EEG = pop_loadset('filename','Walking_Anxiety_eventchan.set','filepath','C:\\Users\\Zeno\\Desktop\\VRCodesMain\\');
EEG = eeg_checkset( EEG );
%Loading Electrodes file
s.elocs_file = [s.subj_data_path '/MFPRL_default.sfp'];

%From MFPRL_default.sfp file, changing the channel names to channel no.s
EEG=pop_chanedit(EEG,'changefield',{1 'labels' 'Fp1'},'changefield',{2 'labels' 'Fz'},...
    'changefield',{3 'labels' 'F3'},'changefield',{4 'labels' 'F7'},...
    'changefield',{5 'labels' 'LHEye'},'changefield',{6 'labels' 'FC5'},...
    'changefield',{7 'labels' 'FC1'},'changefield',{8 'labels' 'C3'},...
    'changefield',{9 'labels' 'T7'},'changefield',{10 'labels' 'GND'},... % CHANGE GND TO FPZ
    'changefield',{11 'labels' 'CP5'},'changefield',{12 'labels' 'CP1'},...
    'changefield',{13 'labels' 'Pz'},'changefield',{14 'labels' 'P3'},...
    'changefield',{15 'labels' 'P7'},'changefield',{16 'labels' 'O1'},...
    'changefield',{17 'labels' 'Oz'},'changefield',{18 'labels' 'O2'},...
    'changefield',{19 'labels' 'P4'},'changefield',{20 'labels' 'P8'},...
    'changefield',{21 'labels' 'CP6'},'changefield',{22 'labels' 'CP2'},...
    'changefield',{23 'labels' 'Cz'},'changefield',{24 'labels' 'C4'},...
    'changefield',{25 'labels' 'T8'},'changefield',{26 'labels' 'RHEye'},...
    'changefield',{27 'labels' 'FC6'},'changefield',{28 'labels' 'FC2'},...
    'changefield',{29 'labels' 'F4'},'changefield',{30 'labels' 'F8'},...
    'changefield',{31 'labels' 'Fp2'},'changefield',{32 'labels' 'AF7'},...
    'changefield',{33 'labels' 'AF3'},'changefield',{34 'labels' 'AFz'},...
    'changefield',{35 'labels' 'F1'},'changefield',{36 'labels' 'F5'},...
    'changefield',{37 'labels' 'FT7'},'changefield',{38 'labels' 'FC3'},...
    'changefield',{39 'labels' 'FCz'},'changefield',{40 'labels' 'C1'},...
    'changefield',{41 'labels' 'C5'},'changefield',{42 'labels' 'TP7'},...
    'changefield',{43 'labels' 'CP3'},'changefield',{44 'labels' 'P1'},...
    'changefield',{45 'labels' 'P5'},'changefield',{46 'labels' 'Lneck'},...
    'changefield',{47 'labels' 'PO3'},'changefield',{48 'labels' 'POz'},...
    'changefield',{49 'labels' 'PO4'},'changefield',{50 'labels' 'Rneck'},...
    'changefield',{51 'labels' 'P6'},'changefield',{52 'labels' 'P2'},...
    'changefield',{53 'labels' 'CPz'},'changefield',{54 'labels' 'CP4'},...
    'changefield',{55 'labels' 'TP8'},'changefield',{56 'labels' 'C6'},...
    'changefield',{57 'labels' 'C2'},'changefield',{58 'labels' 'FC4'},...
    'changefield',{59 'labels' 'FT8'},'changefield',{60 'labels' 'F6'},...
    'changefield',{61 'labels' 'F2'},'changefield',{62 'labels' 'AF4'},...
    'changefield',{63 'labels' 'RVEye'});

%Changing channel location structure in EEG dataset using the file <MFPRL_default.sfp>
EEG=pop_chanedit(EEG, 'lookup', s.elocs_file);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
eeglab redraw
eeg_checkset(EEG);

%Adding the IC components
EEG.good = good;  
EEG.eyes = eyes;
EEG.bad  = bad;  
EEG.icaact = icaact;
EEG.icawinv = icawinv;
EEG.icasphere = icasphere;
EEG.icaweights = icaweights;
EEG.icachansind = icachansind;

% backprojection in continous data
EEG = pop_subcomp( EEG, EEG.bad, 0);
%Saving the Continous Backprojected Anxiety Data
name = 'Walking_Anxiety_backproject_continous'; % update based on current file
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname',name,...
    'savenew',[s.subj_data_path '/' name '.set'],'gui','off','overwrite','on'); 
eeglab redraw